## Information details of yourself

# Your name displaying as the navbar brand
name: hyperzsb
# The custom text displaying as the title of the window
windowTitle: hyperzsb's ideas
# Your brief self introduction displaying on the Home page (keep it simple for better appearance)
introduction:
  main: Hi, here is hyperzsb
  sub: I am a free developer 👨‍💻 (also still a student 👨‍🎓), interested in fullstack, Blockchain, Web 3, DevOps, and other state-of-the-art technologies.
# Your social media details displaying on the footer (if not applicable, leave it blank)
socialMedia:
  email: hyperzsb@qq.com
  twitter: hyperzsb
  facebook:
  instagram:
  youtube: UCpFjl9dlLOTEa99rKV7trrQ
  github: Hyperzsb
# Copyright details displaying on the footer
copyright: 2022 © hyperzsb

## Basic build and deploy settings

# The URL name of your site. E.g.: https://hyperzsb.io
# This option MUST be modified according to your deployment because the jekyll-sitemap plugin depends on it to generate correct sitemap
url: http://127.0.0.1:4000
# The base route of your site. E.g.: https://hyperzsb.github.io/natalia-theme
baseUrl: /natalia-theme
# Navigation items
navigation:
  - name: Home
    url: /
  - name: Projects
    url: /projects
  - name: Posts
    url: /posts
  - name: Contact
    url: /contact
# Gitalk settings. For more details, please refer to https://github.com/gitalk/gitalk
gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  # Only support single admin, or you can config it manually
  admin:
# EmailJS setting. For more details, please refer to https://www.emailjs.com/
emailjs:
  userID:
  serviceID:
  templateID:
# Miscellaneous settings
setting:
  enableLoadingModal: true
  # Dark mode has not developed completely yet. Please do not turn it on
  enableDarkMode: false
# Timezone setting
timezone: Asia/Shanghai
# Display future posts
future: false

## Advanced build and deploy settings
# Plugins enabled
plugins:
  # A Jekyll plugin to generate an Atom (RSS-like) feed of your Jekyll posts. For more details, please refer to https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  # A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content. For more details, please refer to https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag
  # A Jekyll plugin to generate a sitemaps.org compliant sitemap for your Jekyll site. For more details, please refer to https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
  # A Jekyll plugin to support Emoji contents. For more details, please refer to https://github.com/jekyll/jemoji
  - jemoji

collections:
  pages:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      permalink: /posts/:title:output_ext
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project
  - scope:
      path: ""
    values:
      layout: default
# Exclude following files/directories when building
exclude:
  - CHANGELOG.md
  - LICENSE
  - README.md
