## Information details of yourself

# Your name displaying as the navbar brand
name: hyperzsb
# The custom text displaying as the title of the window
windowTitle: hyperzsb's ideas
# Your brief self introduction displaying on the Home page (keep it simple for better appearance)
introduction:
  main: Hi, here is hyperzsb
  sub: I am a free developer 👨‍💻 (also still a student 👨‍🎓) from China 🇨🇳. I have great interests in Web Fullstack, Blockchain, Web 3, DevOps, and other state-of-the-art technologies 🛠.
# Your social media details displaying on the footer (if not applicable, leave it blank)
socialMedia:
  # Your email address, e.g. <host name>@<domain name>
  email: hyperzsb@qq.com
  # Your facebook id, e.g. <userid>
  facebook: hyperzsb
  # Your GitHub id, e.g. <userid>
  github: Hyperzsb
  # Your Instagram id, e.g. <userid>
  instagram:
  # Your Linkedin user identifier, e.g. <firstname>-<lastname>-<integer identifier>
  linkedin: shaobo-zhang-584716252
  # Your stackoverflow user identifier, e.g. <integer identifier>/<username>
  stackoverflow:
  # Your Twitter id, e.g. <userid>
  twitter: hyperzsb
  # Your WhatsApp phone number; e.g. if your phone number is +1 123 456, just put 1123456 here
  whatsapp:
  # Please use your channel ID instead of your username
  youtube:
# Copyright details displaying on the footer
copyright: 2022 © hyperzsb

## Basic build and deploy settings

# The URL name of your site. E.g.: https://hyperzsb.io
# This option MUST be modified according to your deployment because the jekyll-sitemap plugin depends on it to generate correct sitemap
url: https://hyperzsb.io
# Navigation items
navigation:
  - name: Home
    url: /
  - name: Projects
    url: /projects
  - name: Posts
    url: /posts
  - name: Contact
    url: /contact
# Gitalk settings. For more details, please refer to https://github.com/gitalk/gitalk
gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  # Only support single admin, or you can config it manually
  admin:
# EmailJS setting. For more details, please refer to https://www.emailjs.com/
emailjs:
  userID:
  serviceID:
  templateID:
# Clarity setting. For more details, please refer to https://clarity.microsoft.com/
clarity:
  enable:
  projectID:
# Miscellaneous settings
setting:
  # Show a loading modal when loading of pages is not completed
  # If you do not want to use the loading modal, just set it to false
  enableLoadingModal: false
  # Enable a dark theme option at the end of the page (supporting auto-detection of system theme)
  # If you do not want to use the dark theme, just set it to false
  enableDarkMode: true
# Timezone setting
timezone: Asia/Shanghai
# Display future posts
future: false

## Advanced build and deploy settings
# Plugins enabled
plugins:
  # A Jekyll plugin to generate an Atom (RSS-like) feed of your Jekyll posts. For more details, please refer to https://github.com/jekyll/jekyll-feed
  - jekyll-feed
  # A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content. For more details, please refer to https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag
  # A Jekyll plugin to generate a sitemaps.org compliant sitemap for your Jekyll site. For more details, please refer to https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
  # A Jekyll plugin to support Emoji contents. For more details, please refer to https://github.com/jekyll/jemoji
  - jemoji

collections:
  # The collection of "biography" currently includes a section called "Biography" in the home page
  biographies:
    output: false
  pages:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      type: post
      layout: post
      permalink: /posts/:title/
      toc: true
      comment: true
      pinned: false
      top: false
  # Pages inside `_posts` directory are project pages, and they will ues the default layout `project`
  - scope:
      path: "_projects"
      type: projects
    values:
      type: project
      layout: project
      permalink: /projects/:title/
      pinned: false
  # This is a wildcard setting, pages in other directory will use the default layout `default`
  - scope:
      path: ""
    values:
      layout: default
# Exclude following files/directories when building
exclude:
  - CHANGELOG.md
  - LICENSE
  - README.md
