url: http://127.0.0.1:4000

name: hyperzsb

copyright: 2022 © hyperzsb

socialMedia:
  email: hyperzsb@qq.com
  twitter: hyperzsb
  facebook: hyperzsb
  instagram: hyperzsb
  youtube: hyperzsb
  github: Hyperzsb

navigation:
  - name: Home
    url: /
  - name: Blog
    url: /blog
  - name: Contact
    url: /contact

setting:
  enableLoadingModal: true
  # Dark mode has not developed completely yet. Please do not turn it on.
  enableDarkMode: false